CREATE TABLE permit (
  id                      UUID PRIMARY KEY,
  permit_number           VARCHAR(64) NOT NULL UNIQUE,
  permit_type             VARCHAR(64) NOT NULL,
  applicant_company_id    UUID NOT NULL,
  applicant_premise_id    UUID NOT NULL,
  applicant_name          VARCHAR(255) NOT NULL,
  chemical_id             UUID NOT NULL,
  chemical_name           VARCHAR(255) NOT NULL,
  batch_id                UUID,
  movement_id             UUID,
  quantity                NUMERIC(18, 6),
  unit                    VARCHAR(16),
  purpose                 TEXT,
  country_of_origin       VARCHAR(128),
  port_of_entry           VARCHAR(128),
  destination_premise_id  UUID,
  sender_premise_id       UUID,
  receiver_premise_id     UUID,
  transporter_premise_id  UUID,
  license_id              UUID,
  license_number          VARCHAR(64),
  license_type            VARCHAR(64),
  license_valid_from      DATE,
  license_valid_until     DATE,
  status                  VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  submitted_at            TIMESTAMPTZ,
  reviewed_by             VARCHAR(128),
  reviewed_at             TIMESTAMPTZ,
  approved_at             TIMESTAMPTZ,
  valid_from              DATE,
  valid_until             DATE,
  conditions              TEXT,
  review_notes            TEXT,
  rejection_reason        TEXT,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by              VARCHAR(128),
  version                 BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_permit_applicant ON permit (applicant_premise_id);
CREATE INDEX idx_permit_chemical ON permit (chemical_id);
CREATE INDEX idx_permit_status ON permit (status);
